version: "3.9"

services:
  web:
    image: online-courses-web:latest
    environment:
      DJANGO_SECRET_KEY: "dev-secret-key-change-me"
      DJANGO_DEBUG: "0"
      POSTGRES_DB: "online_courses"
      POSTGRES_USER: "online_user"
      POSTGRES_PASSWORD: "online_password"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - main_net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  worker:
    image: online-courses-web:latest
    command: celery -A config worker -l info
    environment:
      DJANGO_SECRET_KEY: "dev-secret-key-change-me"
      DJANGO_DEBUG: "0"
      POSTGRES_DB: "online_courses"
      POSTGRES_USER: "online_user"
      POSTGRES_PASSWORD: "online_password"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
    networks:
      - main_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "online_courses"
      POSTGRES_USER: "online_user"
      POSTGRES_PASSWORD: "online_password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_net
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7-alpine
    networks:
      - main_net
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - main_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  static_volume:

networks:
  main_net:
    driver: overlay
